// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPackUpdater.Context;

namespace WebPackUpdater.Migrations
{
    [DbContext(typeof(WebResourceContext))]
    [Migration("20181113123526_builds")]
    partial class builds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebPackUpdater.Model.Build", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BuildDescription");

                    b.Property<string>("BuildLog");

                    b.Property<string>("BuildName");

                    b.HasKey("Id");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("WebPackUpdater.Model.ChangedWebResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BuildId");

                    b.Property<DateTime>("ChangedDate");

                    b.Property<Guid?>("WebResourceMapId");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("WebResourceMapId");

                    b.ToTable("ChangedWebResources");
                });

            modelBuilder.Entity("WebPackUpdater.Model.WebResourceMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("CrmFileName");

                    b.Property<Guid>("CrmWebResourceId");

                    b.Property<string>("FileSystemPath");

                    b.Property<bool>("IsAutoUpdate");

                    b.Property<string>("LocalFileMd5Hash");

                    b.HasKey("Id");

                    b.ToTable("WebResourceMaps");
                });

            modelBuilder.Entity("WebPackUpdater.Model.ChangedWebResource", b =>
                {
                    b.HasOne("WebPackUpdater.Model.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId");

                    b.HasOne("WebPackUpdater.Model.WebResourceMap", "WebResourceMap")
                        .WithMany()
                        .HasForeignKey("WebResourceMapId");
                });
#pragma warning restore 612, 618
        }
    }
}
